### ISSUE TITLE
intput format

### ISSUE THREAD

**Issue by zuodabin** [slimsuite/deduce#1]
Dear author, I would like to ask you a question, the input file is in fasta format. I am currently aligning some genomes in maf format, can I convert them to fasta format?

**Comment by slimsuite** [comment]
I don't really understand the question, sorry. You do not want aligned genomes as input, so use the original genome fasta files.

**Comment by zuodabin** [comment]
That means I just have to put multiple genome files in one directory, right?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "slimsuite/deduce"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月30日(星期二) 晚上9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [slimsuite/deduce] intput format (Issue #1)





 
I don't really understand the question, sorry. You do not want aligned genomes as input, so use the original genome fasta files.

**Comment by slimsuite** [comment]
Yes, that is correct. One fasta per genome. You should be able to use hard or soft links to the genome fastas if you do not want to copy them.

**Comment by zuodabin** [comment]
Thank you for your reply. With best wishes
1187697462
***@***.***
---- Replied Message ----
***@***.***>Date7/30/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [slimsuite/deduce] intput format (Issue #1)
Yes, that is correct. One fasta per genome. You should be able to use hard or soft links to the genome fastas if you do not want to copy them.

**Comment by slimsuite** [comment]
No worries.
